<?php
namespace common\components;

//use common\component\jdf;
use backend\models\Profile;
use PHPUnit\Framework\Exception;
use yii;
use yii\base\Component;
//use frontend\models\TblPricing;
//USE frontend\models\TblMessage;
//use frontend\models\TblFile;

class General extends Component
{
//send sms
    public function sendSms($textSms,$phoneNumber){
        try {

            date_default_timezone_set("Asia/Tehran");

            include_once(__DIR__.'/SmsIR_SendMessage.php');

            $APIKey = "2cca397481eefce81db43db3";
            $SecretKey = "qar!ar!D@A*D&3%%4#Safe&moamele";
            $LineNumber = "30004005002888";

            // your mobile numbers
            $profile=Profile::find()->all();
            
            $i=0;
            foreach ($profile as $p){
                
                $phoneNumber[$i]=$p->mobile .'';

                $i++;
            }
            //چون در بالا همه شماره هارو در یک آرایه میریزیم اینجا دیگه اتزم نیسن دوباره اون رو در ارایه بریزیم
            $MobileNumbers = $phoneNumber;
//            var_dump($MobileNumbers);exit;

            // your text messages
            //در اینجا احتیاج تیست به صورت آرایه برگردونیم
            $Messages =array($textSms) ;

            // sending date
            @$SendDateTime = date("Y-m-d")."T".date("H:i:s");

            $SmsIR_SendMessage =new SmsIR_SendMessage($APIKey,$SecretKey,$LineNumber);
            $SendMessage = $SmsIR_SendMessage->SendMessage($MobileNumbers,$Messages,$SendDateTime);
//            var_dump($SendMessage);

        } catch (Exception $e) {
            echo 'Error SendMessage : '.$e->getMessage();
        }


    }

    
//    private $session;
//
//    public function init()
//    {
//        parent::init(); // TODO: Change the autogenerated stub
//        $this->session = yii::$app->session;
//    }
//
//    public function role_user()
//    {
//        $rule = Yii::$app->authManager->getRolesByUser(Yii::$app->user->getId());
//        $i = 1;
//
//        foreach ($rule as $p) {
//            $x[$i] = $p;
//            $i = $i + 1;
//        }
//        if ($i == 1) {
//            $role_user = 'null';
//        } else {
//            $role_user = $x[1]->name;
//        }
//
//
//        return $role_user;
//    }
//
//    public function timeMake($date)
//    {
//        $arr=explode(" ",$date);
//        $arr1=explode("/",$arr[0]);
//        $arr2=explode(":",$arr[1]);
//        return mktime( $arr2[0],  $arr2[1],  $arr2[2],  $arr1[1],  $arr1[2],  $arr1[0]);
//    }
//
//    public function download()
//    {
//
//        $url = yii::getAlias('@upload') . '/order67.rar';
//        return yii::$app->response->sendFile($url);
//    }
//
//    public function redirectt($url)
//    {
//        if (!headers_sent()) {
//            header('Location: ' . $url);
//            exit;
//        } else {
//            echo '<script type="text/javascript">';
//            echo 'window.location.href="' . $url . '";';
//            echo '</script>';
//            echo '<noscript>';
//            echo '<meta http-equiv="refresh" content="0;url=' . $url . '" />';
//            echo '</noscript>';
//            exit;
//        }
//    }



//    public function pricing($id_order, $subject, $reshte, $type_work, $orientation = nuul, $id_userr = null)
//    {
//        $model = new TblPricing();
//        $model->id_partners = 0;
//        $model->id_user = $id_userr;
//        $model->end_pricing = 0;
//        $model->id_order = $id_order;
//        $model->subject = $subject;
//        $model->reshte = $reshte;
//        if ($orientation == null) {
//            $model->orientation = 'ندارد';
//        } else {
//            $model->orientation = $orientation;
//        }
//        $model->type_work = $type_work;
//        $model->reject_user = 0;
//        $model->date = date('y-m-d');
//        $date_ir = new jdf();
//        $model->date_ir = $date_ir->date('Y/m/d');
//        $model->enabel = 1;
//        if ($model->save()) {
//            $this->session['info'] .= '';
//            return 1;
//        } else {
//            $this->session['error'] .= '';
//            return 0;
//        }
//    }
//
//    public function uploadfile($namefile, $id_order, $subject = null, $description = null, $access = null, $id_functor = null, $id_teict = null, $send_type = null, $id_viewer = null, $section = null)
//    {
//        $model = new TblFile();
//
//        $model->id_order = $id_order;
//        $model->section = $section;
//        $model->name = $namefile;
//        $model->subject = $subject;
//        $model->description = $description;
//        $model->access = $access;
//        $model->id_functor = $id_functor;
//        $model->id_teict = $id_teict;
//        $model->send_type = $send_type;
//        $model->id_viewer = $id_viewer;
//        $model->date = date('Y-m-d');
//        $jdf = new jdf();
//        $model->date_ir = $jdf->date('y/m/d');
//        $model->enabel = 1;
//        if ($model->save()) {
//            $this->session['info'] .= '';
//            return 1;
//        } else {
//            $this->session['error'] .= '';
//            return 2;
//        }
//    }
//
//    public function sendsms($to, $body)
//    {
//
//
//        $client = new \SoapClient("http://smssend.ir/smsSendWebServiceforphp.asmx?wsdl");
//
//        $params = array('UserName' => 'bahram333',
//            'Pass' => 'amirali333',
//            'Domain' => 'smssend',
//            'SmsText' => array($body),
//            'MobileNumber' => array($to),
//            'SenderNumber' => '500012995',
//            'sendType' => 'StaticText',
//            'smsMode' => 'SaveInPhone');
//        $result = $client->SendSms($params)->SendSmsResult;
//
//        if ($result->long > 0) {
//            $this->session['info'] .= '';
//            return 1;
//        } else {
//            $this->session['error'] .= '';
//            return 0;
//        }
//    }
//
//
//    public function sendmail($to, $subject, $body, $attach = null)
//    {
//        $validator = new yii\validators\EmailValidator();
//
//        if ($validator->validate($to)) {
//            if ($attach == null) {
//                $result = Yii::$app->mailer->compose()
//                    ->setTo($to)
//                    ->setFrom(['admin@istgahfani.com' => 'ایستگاه فنی'])
//                    ->setSubject($subject)
//                    ->setCharset('utf8')
//                    ->setHtmlBody($body)
//                    ->send();
//                return ($result);
//            }
//            if ($attach != null) {
//                $result = Yii::$app->mailer->compose()
//                    ->setTo($to)
//                    ->setFrom(['admin@istgahfani.com' => 'ایستگاه فنی'])
//                    ->setSubject($subject)
//                    ->setCharset('utf8')
//                    ->setHtmlBody($body)
//                    ->attach($attach)
//                    ->send();
//                return ($result);
//            }
//            $this->session['info'] .= '';
//
//
//        } else {
//            $this->session['error'] .= '';
//            return (0);
//        }
//    }
//
//    public function alret()
//    {
//        $masg = '';
//        if (isset($_SESSION['info'])) {
//            $masg .= '<div class="alert alert-info">';
//            $masg .= $_SESSION['info'];
//            unset($_SESSION['info']);
//            $masg .= '</div>';
//        }
//        if (isset($_SESSION['error'])) {
//            $masg .= '<div class="alert alert-warning">';
//            $masg .= $_SESSION['error'];
//            unset($_SESSION['error']);
//            $masg .= '</div>';
//        }
//        if (isset($_SESSION['danger'])) {
//            $masg .= '<div class="alert alert-danger">';
//            $masg .= $_SESSION['danger'];
//            unset($_SESSION['danger']);
//            $masg .= '</div>';
//        }
//
//        return $masg;
//
//
//    }
//
//    public function message($level, $id_order, $subject, $id_viewer = null)
//    {
//
//        if ($level == 1) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'سفارش جدید ثبت شده است خواهشا اقدام لازم را به عمل آورید';
//            $model->id_viewer = 0;
//            $model->admin_view = 1;
//            $model->what_part = 'خواهشمند است به قسمت تعین قیمت مراجعه کنید و برای سفارش تایید شده تعین قیمت  کنید';
//            $model->part_send = 'از قسمت ثبت سفارش صادر شده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'سفارش ثبت شدمنتظر قیمت دهی';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ثبت سفارش شما برای کارمندان ارسال شد';
//                return 1;
//            } else {
//                $this->session['error'] .= 'پیام ثبت سفارش شما برای کارمندان ارسال نشد';
//                return 0;
//            }
//        }
//        if ($level == 2) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'یک سفارش جهت تعیین قیمت به شما ارائه شده است خواهشا تعیین قیمت و زمان کنید';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 0;
//            $model->what_part = 'خواهشمند است به قسمت تعین قیمت مراجعه کنید و برای سفارش تایید شده تعین قیمت  کنید';
//            $model->part_send = 'از قسمت تعیین قیمت مدیریت ارسال شده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'محقق جهت تعیین قیمت';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 3) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'سفارش شما تعیین قیمت شد';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 0;
//            $model->what_part = 'خواهشمند است به قسمت سفارشت تعیین قیمت شده مراجعه فرمایید';
//            $model->part_send = 'از قسمت تعیین قیمت مدیریت ارسال شده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'تعیین قیمت توسط کارمندان مدیریت';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 4) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'یکی از سفارش ها تعیین قیمت شد';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 1;
//            $model->what_part = 'خواهشمند است به قسمت سفارش های تعیین قیمت شده مراجعه کنید';
//            $model->part_send = 'از قسمت تعیین قیمت researcher ارسال شده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'تعیین قیمت توسط researcher';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 5) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = ' تعیین قیمت یکی از سفارش ها توسط انجام دهنده کنسل شد';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 1;
//            $model->what_part = 'خواهشمند است به قسمت تعیین قیمت های کنسل شده مراجعه کنید';
//            $model->part_send = 'از قسمت تعیین قیمت researcher ارسال شده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = ' کنسل تعیین قیمت توسط researcher ';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 6) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'سفارش توسط مشتری تایید شد و فاکتور صادر و توسط مشتری پرداخت آنلاین شد';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 1;
//            $model->what_part = 'خواهشمند است به قسمت سفارشات پرداخت شده مراجعه کنید';
//            $model->part_send = 'از قسمت پرداخت آنلاین آمده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'سفارش توسط مشتری تایید و پرداخت شد ';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 7) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'سفارش جهت انجام با قیمت مشخص به شما واگذار شده است';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 0;
//            $model->what_part = 'خواهشمند است به قسمت سفارشات در حال انجام مراجعه کنید';
//            $model->part_send = 'از قسمت واگذاری سفارش مدیریت آمده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'قسمتی از سفارش به انجام دهنده واگذار شد';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 8) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'انجام دهنده کار را جهت تحویل آماده کرده است';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 1;
//            $model->what_part = 'خواهشمند است به قسمت سفارشات آماده تحویل مراجعه کنید';
//            $model->part_send = 'از قسمت تحویل کار researcher آمده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'researcher کار را آماده کرد';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 9) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'کار شما آماده تحویل است';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 0;
//            $model->what_part = 'خواهشمندیم به قسمت تحویل سفارش مراجعه کنید ';
//            $model->part_send = 'از قسمت تحویل کار researcher آمده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'کار به مشتری تحویل داده شد';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 10) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'فاکتور صادر شده بابت تحویل کار شماست لطفا پرداخت کنید و کار خود را به صورت آنلاین تحویل بگیرید ';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 0;
//            $model->what_part = 'خواهشمندیم به قسمت تحویل سفارش مراجعه کنید ';
//            $model->part_send = 'از قسمت تحویل کار researcher آمده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'کار به مشتری تحویل داده شد';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//
//        if ($level == 11) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'مشتری هزینه را پرداخت و فایل را دریافت کرد ';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 1;
//            $model->what_part = 'جهت اطلاع شماست';
//            $model->part_send = 'تحویل کار به مشتری';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'فاکتور توسط مشتری پرداخت و تحویل کار شد';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 12) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'مشتری این قسمت را پذیرفته و ادامه کار را خواستار است';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 1;
//            $model->what_part = 'خواهشمند است به قسمت سفارشات در حال انجام مراجعه فرمایید';
//            $model->part_send = 'از قسمت کارهای در حال انجام مشتری آمده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'این قسمت توسط مشتری تایید شد';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 13) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'به انجام دهنده اطلاع داده شد و ادامه کار را تایید کرد';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 1;
//            $model->what_part = 'خواهشمند است به قسمت سفارشات در حال انجام مراجعه فرمایید';
//            $model->part_send = 'از قسمت کارهای در حال انجام researcher آمده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'انجام دهنده ادامه کار را استارت زد';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//        }
//        if ($level == 14) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'انجام ادامه کار به انجام دهنده واگذار شد';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 0;
//            $model->what_part = 'خواهشمند است به قسمت سفارشات در حال انجام مراجعه فرمایید';
//            $model->part_send = 'از قسمت کارهای در حال انجام مدیریت آمده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'ادامه کار به انجام دهنده واگذار شد';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//
//
//        }
//
//        if ($level == 15) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'برای انجام دهنده ادامه کار ارسال شد';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 0;
//            $model->what_part = 'صرفا جهت اطلاع';
//            $model->part_send = 'از قسمت کارهای در حال انجام مدیریت آمده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'پیام ادامه کار برای انجام دهنده ارسال شد';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//
//
//        }
//        if ($level == 16) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'یک تیکت جدید از طرف مشتری یا researcher صادر شده است';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 1;
//            $model->what_part = 'خواهشا به قسمت پشتیبانی مراجعه کنید';
//            $model->part_send = 'از قسمت پشتیبانی کاربر ارسال شده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = ' پیام پشتیبانی از طرف یوزریا researcher';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//
//
//        }
///// یک تیکت برای اطلاع مشتری صادر شده است
//        if ($level == 17) {
//            $model = new TblMessage();
//            $model->subject = $subject;
//            $model->description = 'یک تیکت برای مشتری ارسال شده است';
//            $model->id_viewer = $id_viewer;
//            $model->admin_view = 0;
//            $model->what_part = 'خواهشا به قسمت پشتیبانی مراجعه کنید';
//            $model->part_send = 'از قسمت پشتیبانی مدیریت ارسال شده است';
//            $model->id_send = yii::$app->user->getId();
//            $model->date = date('Y-m-d');
//            $date_ir = new jdf();
//            $model->date_ir = $date_ir->date('Y/m/d');
//            $model->enabel = 1;
//            $model->thework = 'پیام پشتیبانی از طرف مدیریت';
//            $model->id_order = $id_order;
//            $model->enabel_order = 1;
//            $model->save();
//            if ($model->save()) {
//                $this->session['info'] .= 'پیام ارسال شد' . '<br/>';
//                return 1;
//            } else {
//                $this->session['error'] .= 'متاسفانه پیام ارسال نشد' . '<br/>';
//                return 0;
//            }
//
//
//        }
//    }

}

